#if 0
//*
THIS IS A FILE THAT BELONGS TO THE LIST OF EXERCISES
FOR LEARNING C LANGUAGE ON THE COURSE PROGRAMMING LOGIC MANAGED BY PROFESSOR SAULO SANTOS.

STUDENT NAME: YITZHAK B. SOLORZANO
EXERCISE: 02 / BASIC STAGE
TOPIC: ON THIS EXERCISE PROFESSOR SAULO EXPLAINED HOW TO SETUP THE DEV C++ APP
ASSIGNMENT DATE: APRIL 30, 2023
DUE DATE: MAY 7, 2023

***** IMPORTANT THAT I'M USING VISUAL STUDIO CODE TO FOLLOW THE COURSE SO I'VE SKIPED THIS PART ******

*//
#endif

#include <stdio.h>
#include <locale.h>

int main(int argc, char *argv[])
{
    setlocale(LC_ALL, "en-US");
    return (0);
}