/*
*THIS IS A FILE THAT BELONGS TO THE LIST OF EXERCISES
*FOR LEARNING C LANGUAGE ON THE COURSE PROGRAMMING LOGIC MANAGED BY PROFESSOR *SAULO SANTOS.
*
*STUDENT NAME: YITZHAK B. SOLORZANO
*EXERCISE: 06
*TOPIC: PROFESSOR SAULO EXPLAINED HOW COMPILATION WORKS AND EACH STAGE OF *COMPILATION.
*ASSIGNMENT DATE: APRIL 30, 2023
*DUE DATE: MAY 7, 2023
*/


#include <stdio.h>
#include <locale.h>

int main(void)
{
    setlocale(LC_ALL, "en-US");

}